export const postsData = [
  {
    id: 1,
    user: 'nature_lover',
    image_url:
      'https://images.unsplash.com/photo-1603105402889-eee36ee6406b?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    description: 'Exploring the wilderness! 🌲 #nature #adventure',
    likes: 120,
    comments: [
      {
        user: 'hiker22',
        text: 'What a breathtaking view!',
        timestamp: '2023-07-28T12:34:56',
      },
      {
        user: 'travel_bug',
        text: 'Nature at its best!',
        timestamp: '2023-07-28T14:15:30',
      },
    ],
    timestamp: '2023-07-28T10:30:00',
  },
  {
    id: 2,
    user: 'foodie_adventures',
    image_url:
      'https://images.unsplash.com/photo-1577141173722-d07075bced3a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80',
    description:
      'Indulging in some delectable desserts! 🍨 #foodie #dessertlover',
    likes: 88,
    comments: [
      {
        user: 'dessert_queen',
        text: 'Yummylicious!',
        timestamp: '2023-07-28T11:45:20',
      },
      {
        user: 'sweet_tooth',
        text: 'I want some too!',
        timestamp: '2023-07-28T12:00:05',
      },
    ],
    timestamp: '2023-07-28T09:15:00',
  },
  {
    id: 3,
    user: 'travel_junkie',
    image_url:
      'https://images.unsplash.com/photo-1589194837737-f0e1026311c3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    description: 'Lost in the streets of Tokyo! 🗼 #travel #wanderlust',
    likes: 150,
    comments: [
      {
        user: 'globe_trotter',
        text: 'Tokyo is amazing!',
        timestamp: '2023-07-28T10:50:30',
      },
      {
        user: 'adventure_awaits',
        text: 'What an adventure!',
        timestamp: '2023-07-28T11:15:00',
      },
    ],
    timestamp: '2023-07-28T08:45:00',
  },
  {
    id: 4,
    user: 'pet_lover',
    image_url:
      'https://images.unsplash.com/photo-1589656966895-2f33e7653819?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1740&q=80',
    description: 'My furry best friend! 🐾 #pets #doglover',
    likes: 200,
    comments: [
      {
        user: 'animal_whisperer',
        text: 'Adorable!',
        timestamp: '2023-07-28T13:20:10',
      },
      {
        user: 'pet_obsessed',
        text: "Can't handle the cuteness!",
        timestamp: '2023-07-28T14:00:45',
      },
    ],
    timestamp: '2023-07-28T07:30:00',
  },
  {
    id: 5,
    user: 'fitness_guru',
    image_url:
      'https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    description: 'Morning workout session! 💪 #fitness #healthyliving',
    likes: 80,
    comments: [
      {
        user: 'workout_addict',
        text: 'Keep it up!',
        timestamp: '2023-07-28T09:45:20',
      },
      {
        user: 'fitness_enthusiast',
        text: "You're an inspiration!",
        timestamp: '2023-07-28T10:00:05',
      },
    ],
    timestamp: '2023-07-28T06:15:00',
  },
  {
    id: 6,
    user: 'artistic_eye',
    image_url:
      'https://images.unsplash.com/photo-1557933488-c8daa2a5772c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=774&q=80',
    description: 'Creating magic with colors! 🎨 #art #painting',
    likes: 115,
    comments: [
      {
        user: 'art_lover',
        text: 'Absolutely stunning!',
        timestamp: '2023-07-28T11:10:40',
      },
      {
        user: 'creative_soul',
        text: 'Love your art!',
        timestamp: '2023-07-28T11:30:15',
      },
    ],
    timestamp: '2023-07-28T05:00:00',
  },
];

export const chatData = [
  {
    name: 'John Doe',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: '2 hours ago',
  },
  {
    name: 'Jane Smith',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: '1 day ago',
  },
  {
    name: 'Mike Johnson',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: 'just now',
  },
  {
    name: 'Emily Brown',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: '3 hours ago',
  },
  {
    name: 'Alex Wilson',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: '5 hours ago',
  },
  {
    name: 'Sarah Davis',
    profileIconUrl:
      'https://beforeigosolutions.com/wp-content/uploads/2021/12/dummy-profile-pic-300x300-1.png',
    lastSeen: '2 days ago',
  },
];

export const profilesData = {
  girls: [
    {
      name: 'Alisha',
      age: 24,
      description: 'Adventure seeker | Dog lover 🐶 | Foodie 🍕',
      city: 'Mumbai',
      imageurl: require('../../assets/test-images/01.jpg'),
      likes: 350,
      dislikes: 50,
      goal: 'Travel the world and become a successful entrepreneur.',
      looking_for: 'Relationship',
    },
    {
      name: 'Priya',
      age: 27,
      description: 'Travel enthusiast | Bookworm 📚 | Coffee addict ☕',
      city: 'Bangalore',
      imageurl: require('../../assets/test-images/02.jpg'),
      likes: 420,
      dislikes: 60,
      goal: 'Find a soulmate and start a happy family.',
      looking_for: 'Relationship',
    },
    {
      name: 'Sneha',
      age: 22,
      description: 'Fitness freak | Music lover 🎵 | Nature admirer 🌳',
      city: 'Delhi',
      imageurl: require('../../assets/test-images/03.jpg'),
      likes: 290,
      dislikes: 20,
      goal: 'Become a successful fitness trainer and inspire others to lead a healthy lifestyle.',
      looking_for: 'Friendship',
    },
    {
      name: 'Riya',
      age: 29,
      description: 'Artist | Movie buff 🎬 | Wanderlust ✈️',
      imageurl: require('../../assets/test-images/04.jpg'),
      city: 'Kolkata',
      likes: 500,
      dislikes: 40,
      goal: 'Establish myself as a renowned painter and showcase my art worldwide.',
      looking_for: 'Relationship',
    },
    {
      name: 'Neha',
      age: 25,
      description: 'Tech geek | Gamer 🎮 | Book lover 📖',
      city: 'Pune',
      imageurl: require('../../assets/test-images/05.jpg'),
      likes: 320,
      dislikes: 30,
      goal: 'Build innovative software and contribute to the tech industry.',
      looking_for: 'Relationship',
    },
    {
      name: 'Ananya',
      age: 26,
      description: 'Foodie | Fitness enthusiast 💪 | Beach lover 🏖️',
      imageurl: require('../../assets/test-images/06.jpg'),
      city: 'Goa',
      likes: 450,
      dislikes: 70,
      goal: 'Open a cozy cafe by the beach and enjoy life to the fullest.',
      looking_for: 'Relationship',
    },
    {
      name: 'Isha',
      age: 28,
      description:
        'Nature lover | Animal rights advocate 🐾 | Yoga practitioner 🧘',
      city: 'Jaipur',
      imageurl: require('../../assets/test-images/07.jpg'),
      likes: 380,
      dislikes: 60,
      goal: 'Travel to remote places and promote eco-friendly living.',
      looking_for: 'Relationship',
    },
    {
      name: 'Tanvi',
      age: 23,
      description: 'Photographer | Music lover 🎶 | Dreamer ✨',
      city: 'Chennai',
      imageurl: require('../../assets/test-images/08.jpg'),
      likes: 290,
      dislikes: 40,
      goal: 'Capture emotions through my camera lens and tell captivating stories.',
      looking_for: 'Friendship',
    },
    {
      name: 'Ritu',
      age: 30,
      description: 'Artist | Vintage fashion enthusiast 👗 | Coffee lover ☕',
      city: 'Hyderabad',
      imageurl: require('../../assets/test-images/09.jpg'),
      likes: 400,
      dislikes: 50,
      goal: 'Create a unique fashion brand with a touch of art and elegance.',
      looking_for: 'Relationship',
    },
    {
      name: 'Juhi',
      age: 29,
      description: 'Traveler | Nature lover 🌿 | Adventure enthusiast ⛺',
      city: 'Lucknow',
      imageurl: require('../../assets/test-images/10.jpg'),
      likes: 350,
      dislikes: 30,
      goal: 'Explore the hidden treasures of the world and experience diverse cultures.',
      looking_for: 'Relationship',
    },
  ],
  guys: [
    {
      name: 'Rahul',
      age: 26,
      description: 'Tech geek | Gamer 🎮 | Pizza lover 🍕',
      city: 'Pune',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 250,
      dislikes: 30,
      goal: 'Build innovative technology products and make a positive impact on society.',
      looking_for: 'Relationship',
    },
    {
      name: 'Karan',
      age: 28,
      description: 'Musician | Nature lover 🌿 | Tea enthusiast 🍵',
      city: 'Chennai',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 180,
      dislikes: 20,
      goal: "Compose and produce music that touches people's hearts and souls.",
      looking_for: 'Relationship',
    },
    {
      name: 'Vikram',
      age: 25,
      description: 'Foodie | Fitness enthusiast 💪 | Traveler ✈️',
      city: 'Hyderabad',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 300,
      dislikes: 40,
      goal: "Own a successful restaurant chain and explore the world's diverse cuisines.",
      looking_for: 'Friendship',
    },
    {
      name: 'Aryan',
      age: 29,
      description: 'Adventure seeker | Movie buff 🎬 | Fitness lover 💪',
      city: 'Mumbai',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 380,
      dislikes: 60,
      goal: 'Conquer the highest peaks and inspire others to embrace an active lifestyle.',
      looking_for: 'Relationship',
    },
    {
      name: 'Rohan',
      age: 27,
      description: 'Photographer | Nature lover 🌳 | Coffee enthusiast ☕',
      city: 'Bangalore',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 400,
      dislikes: 50,
      goal: 'Capture the beauty of nature through my lens and showcase it to the world.',
      looking_for: 'Relationship',
    },
    {
      name: 'Amit',
      age: 30,
      description: 'Chef | Food lover 🍽️ | Adventure enthusiast ⛺',
      city: 'Delhi',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 420,
      dislikes: 40,
      goal: 'Innovate new culinary delights and open my own gourmet restaurant.',
      looking_for: 'Relationship',
    },
    {
      name: 'Raj',
      age: 26,
      description: 'Fitness trainer | Sports lover 🏀 | Nature explorer 🌲',
      city: 'Kolkata',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 350,
      dislikes: 30,
      goal: 'Help people achieve their fitness goals and stay healthy.',
      looking_for: 'Friendship',
    },
    {
      name: 'Vishal',
      age: 28,
      description: 'Tech enthusiast | Gamer 🎮 | Music lover 🎵',
      city: 'Ahmedabad',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 280,
      dislikes: 30,
      goal: 'Create innovative tech solutions and make the world a better place.',
      looking_for: 'Relationship',
    },
    {
      name: 'Siddharth',
      age: 29,
      description: 'Artist | Movie buff 🎥 | Nature lover 🌳',
      city: 'Chandigarh',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 320,
      dislikes: 20,
      goal: 'Inspire people through my art and make a positive impact.',
      looking_for: 'Relationship',
    },
    {
      name: 'Kunal',
      age: 27,
      description: 'Traveler | Adventure enthusiast ⛺ | Coffee addict ☕',
      city: 'Jaipur',
      imageurl: 'https://picsum.photos/200/300?random=1',
      likes: 400,
      dislikes: 40,
      goal: 'Explore the unexplored and experience the beauty of the world.',
      looking_for: 'Relationship',
    },
  ],
};
